##
##  Makefile -- Build procedure for sample authz_signedurl Apache module
##  Autogenerated via ``apxs -n authz_signedurl -g''.
##

builddir=.
top_srcdir=/usr/share/httpd
top_builddir=/usr/share/httpd
include /usr/share/httpd/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_authz_signedurl.o mod_authz_signedurl.lo mod_authz_signedurl.slo mod_authz_signedurl.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/authz_signedurl

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

